# Generated by Django 5.2.5 on 2026-09-12 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0007_asignacionpersonal_incidencias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=40, unique=True)),
                ('titulo', models.CharField(max_length=240, verbose_name='tarea')),
                ('detalle', models.TextField(blank=True)),
                ('area', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('MESA_DE_CONTROL', 'Mesa de control'), ('FINANZAS', 'Finanzas'), ('BRADESCARD', 'Bradescard'), ('DIRECCION', 'Dirección'), ('SOPORTE', 'Soporte'), ('RH', 'Recursos humanos'), ('SISTEMAS', 'Sistemas')], default='SISTEMAS', max_length=30, verbose_name='área')),
                ('categoria', models.CharField(choices=[('INCIDENCIA', 'Incidencia'), ('SOLICITUD', 'Solicitud'), ('MEJORA', 'Mejora'), ('TAREA', 'Tarea')], default='TAREA', max_length=20, verbose_name='categoría')),
                ('tipo_trabajo', models.CharField(choices=[('GESTION', 'Gestión'), ('PROYECTO', 'Proyecto'), ('RECURRENTE', 'Recurrente'), ('SOPORTE', 'Soporte')], default='GESTION', max_length=20, verbose_name='tipo de trabajo')),
                ('prioridad', models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], db_index=True, default='MEDIA', max_length=10)),
                ('solicitante', models.CharField(blank=True, max_length=200)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('JUNTA', 'Junta'), ('MEET', 'Meet'), ('LLAMADA', 'Llamada'), ('COMUNICADO', 'Comunicado'), ('SISTEMA', 'Sistema'), ('REVISION_SHEET', 'Revisión de hoja'), ('OTRO', 'Otro')], default='SISTEMA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('EN_ESPERA', 'En espera'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('bloqueo', models.CharField(choices=[('SIN_BLOQUEO', 'Sin bloqueo'), ('PERSONA', 'Persona'), ('AREA', 'Área'), ('BRADESCARD', 'Bradescard'), ('FINANZAS', 'Finanzas'), ('VALIDACION', 'Validación'), ('OTRO', 'Otro')], default='SIN_BLOQUEO', max_length=20)),
                ('bloqueado_por', models.CharField(blank=True, max_length=255, verbose_name='bloqueado por / explicación')),
                ('siguiente_accion', models.TextField(blank=True, verbose_name='siguiente acción')),
                ('fecha_compromiso', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de compromiso')),
                ('fecha_atencion_inicial', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, editable=False, null=True)),
                ('frecuencia', models.CharField(choices=[('UNICA', 'Única'), ('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='UNICA', max_length=15)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='pendientes_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendientes_asignados', to=settings.AUTH_USER_MODEL)),
                ('tda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendientes', to='tickets.tienda', verbose_name='TDA')),
            ],
            options={
                'verbose_name': 'pendiente',
                'verbose_name_plural': 'pendientes',
                'ordering': ['-fecha_creacion', '-pk'],
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PendienteHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tipo_evento', models.CharField(choices=[('CREACION', 'Creación'), ('ESTADO', 'Cambio de estado'), ('RESPONSABLE', 'Cambio de responsable'), ('COMPROMISO', 'Cambio de compromiso'), ('PRIORIDAD', 'Cambio de prioridad'), ('BLOQUEO', 'Cambio de bloqueo'), ('SIGUIENTE_ACCION', 'Cambio de siguiente acción'), ('CIERRE', 'Cierre'), ('REAPERTURA', 'Reapertura'), ('CANCELACION', 'Cancelación'), ('EDICION', 'Edición'), ('COMENTARIO', 'Comentario')], max_length=30)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('comentario', models.TextField(blank=True)),
                ('pendiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='gestor.pendiente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial de pendiente',
                'verbose_name_plural': 'historial de pendientes',
                'ordering': ['-fecha', '-pk'],
                'default_permissions': ('view',),
            },
        ),
        migrations.AddIndex(
            model_name='pendiente',
            index=models.Index(fields=['estado', 'fecha_compromiso'], name='gestor_estado_compromiso'),
        ),
    ]
