# Generated by Django 5.2.5 on 2026-09-03 14:13

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_datos_corporativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.ruta_foto_perfil, verbose_name='foto de perfil'),
        ),
    ]
