# Generated by Django 5.2.5 on 2026-09-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_cerrar',
            field=models.BooleanField(default=True, verbose_name='Cerrar sus tickets con evidencia'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_reasignar',
            field=models.BooleanField(default=False, verbose_name='Reasignar equipo de sus tickets'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_seguimiento',
            field=models.BooleanField(default=True, verbose_name='Actualizar seguimiento de sus tickets'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_ver_todos',
            field=models.BooleanField(default=False, verbose_name='Consultar todos los tickets'),
        ),
    ]
