# Generated by Django 5.2.5 on 2026-09-24 18:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilusuario_puede_cerrar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadLegacyUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_source', models.CharField(max_length=100)),
                ('legacy_id', models.CharField(max_length=120)),
                ('legacy_username', models.CharField(blank=True, max_length=150)),
                ('legacy_email', models.CharField(blank=True, max_length=254)),
                ('legacy_rol', models.CharField(blank=True, max_length=100)),
                ('legacy_activo', models.BooleanField(blank=True, null=True)),
                ('datos_origen', models.JSONField(blank=True, default=dict)),
                ('migrado_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identidades_legacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['legacy_source', 'legacy_id'],
                'constraints': [models.UniqueConstraint(fields=('legacy_source', 'legacy_id'), name='uq_identidad_legacy_source_id')],
            },
        ),
    ]
