# Generated by Django 5.2.5 on 2026-09-24 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_identidad_legacy_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='identidadlegacyusuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('legacy_source', ''), _negated=True), models.Q(('legacy_id', ''), _negated=True)), name='ck_identidad_legacy_source_id_no_vacios'),
        ),
    ]
