# Generated by Django 5.2.5 on 2026-09-24 18:19

import django.db.models.expressions
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_identidad_legacy_identificadores_obligatorios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='identidadlegacyusuario',
            name='uq_identidad_legacy_source_id',
        ),
        migrations.RemoveConstraint(
            model_name='identidadlegacyusuario',
            name='ck_identidad_legacy_source_id_no_vacios',
        ),
        migrations.AddConstraint(
            model_name='identidadlegacyusuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Trim('legacy_source'), django.db.models.functions.text.Trim('legacy_id'), name='uq_identidad_legacy_source_id'),
        ),
        migrations.AddConstraint(
            model_name='identidadlegacyusuario',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.NegatedExpression(django.db.models.lookups.Exact(django.db.models.functions.text.Trim(models.F('legacy_source')), models.Value(''))), django.db.models.expressions.NegatedExpression(django.db.models.lookups.Exact(django.db.models.functions.text.Trim(models.F('legacy_id')), models.Value('')))), name='ck_identidad_legacy_source_id_no_vacios'),
        ),
    ]
