# Generated by Django 5.2.5 on 2026-08-31 05:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('pausa_sla_por_defecto', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstatusOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cuenta_como_afectacion', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=180)),
                ('incidencia_general', models.CharField(blank=True, max_length=255)),
                ('limite_minutos', models.PositiveIntegerField(help_text='Tiempo máximo efectivo de atención en minutos.')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['categoria', 'incidencia_general'],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'incidencia_general'), name='uq_sla_categoria_incidencia')],
            },
        ),
        migrations.CreateModel(
            name='ImportacionTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='importaciones/%Y/%m/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('hash_archivo', models.CharField(db_index=True, max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], default='PROCESANDO', max_length=20)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('nuevos', models.PositiveIntegerField(default=0)),
                ('actualizados', models.PositiveIntegerField(default=0)),
                ('sin_cambios', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('mensaje_error', models.TextField(blank=True)),
                ('iniciado_at', models.DateTimeField(auto_now_add=True)),
                ('finalizado_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-iniciado_at'],
            },
        ),
        migrations.CreateModel(
            name='SubgrupoSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='tickets.gruposoporte')),
            ],
            options={
                'ordering': ['grupo__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True)),
                ('ticket_bradescard', models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True)),
                ('tienda', models.CharField(blank=True, db_index=True, max_length=180)),
                ('estatus_externo', models.CharField(blank=True, db_index=True, max_length=120)),
                ('fecha_apertura_externa', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dias_transcurridos_externo', models.CharField(blank=True, max_length=80)),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=180)),
                ('incidencia_general', models.CharField(blank=True, db_index=True, max_length=255)),
                ('incidencia_especifica', models.TextField(blank=True)),
                ('seguimientos_externos', models.TextField(blank=True)),
                ('fecha_reporte', models.DateField(blank=True, null=True)),
                ('hora_reporte', models.TimeField(blank=True, null=True)),
                ('ultima_modificacion_externa', models.DateTimeField(blank=True, null=True)),
                ('dias_sin_comentar_externo', models.CharField(blank=True, max_length=80)),
                ('tiempo_transcurrido_externo', models.CharField(blank=True, max_length=120)),
                ('asignado_externo', models.CharField(blank=True, max_length=180)),
                ('tipo_externo', models.CharField(blank=True, max_length=120)),
                ('usuario_externo', models.CharField(blank=True, max_length=180)),
                ('tiempo_total_externo', models.CharField(blank=True, max_length=120)),
                ('soc_externo', models.CharField(blank=True, max_length=120)),
                ('tablet_externo', models.CharField(blank=True, max_length=120)),
                ('cierre_por_falta_externo', models.CharField(blank=True, max_length=180)),
                ('datos_origen', models.JSONField(blank=True, default=dict)),
                ('hash_origen', models.CharField(blank=True, db_index=True, max_length=64)),
                ('estado_interno', models.CharField(choices=[('NUEVO', 'Nuevo'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En proceso'), ('EN_ESPERA', 'En espera'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], db_index=True, default='NUEVO', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], db_index=True, default='MEDIA', max_length=20)),
                ('sla_limite_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('sla_segundos_acumulados', models.BigIntegerField(default=0)),
                ('sla_excedido', models.BooleanField(db_index=True, default=False)),
                ('sla_excedido_at', models.DateTimeField(blank=True, null=True)),
                ('asignado_at', models.DateTimeField(blank=True, null=True)),
                ('primer_comentario_at', models.DateTimeField(blank=True, null=True)),
                ('resuelto_at', models.DateTimeField(blank=True, null=True)),
                ('cerrado_at', models.DateTimeField(blank=True, null=True)),
                ('ultima_reapertura_at', models.DateTimeField(blank=True, null=True)),
                ('numero_reaperturas', models.PositiveIntegerField(default=0)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('configuracion_sla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.configuracionsla')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
                ('dependencia_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_actuales', to='tickets.dependencia')),
                ('estatus_operativo_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_actuales', to='tickets.estatusoperativo')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.gruposoporte')),
                ('primera_importacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_primera_importacion', to='tickets.importaciontickets')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('subgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.subgruposoporte')),
                ('ultima_importacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_ultima_importacion', to='tickets.importaciontickets')),
            ],
            options={
                'ordering': ['-creado_at'],
            },
        ),
        migrations.CreateModel(
            name='SegmentoSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ATENCION', 'Atención de soporte'), ('PAUSA', 'Pausa por tercero')], default='ATENCION', max_length=20)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('cuenta_sla', models.BooleanField(default=True)),
                ('motivo', models.TextField(blank=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segmentos_sla', to='tickets.dependencia')),
                ('estatus_operativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segmentos_sla', to='tickets.estatusoperativo')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segmentos_sla', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos_sla', to='tickets.ticket')),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('CREADO', 'Ticket creado'), ('IMPORTADO', 'Ticket importado'), ('ACTUALIZADO_IMPORTACION', 'Actualizado por importación'), ('ASIGNADO', 'Asignado'), ('PRIMER_COMENTARIO', 'Primer comentario'), ('COMENTARIO', 'Comentario'), ('ARCHIVO', 'Archivo agregado'), ('ESTADO', 'Cambio de estado'), ('PRIORIDAD', 'Cambio de prioridad'), ('DEPENDENCIA', 'Cambio de dependencia'), ('ESTATUS_OPERATIVO', 'Cambio de estatus operativo'), ('PAUSA_SLA', 'Pausa SLA'), ('REANUDACION_SLA', 'Reanudación SLA'), ('SLA_EXCEDIDO', 'SLA excedido'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('REABIERTO', 'Reabierto')], db_index=True, max_length=40)),
                ('origen', models.CharField(choices=[('USUARIO', 'Usuario'), ('SISTEMA', 'Sistema'), ('IMPORTACION', 'Importación')], default='SISTEMA', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('valor_anterior', models.JSONField(blank=True, default=dict)),
                ('valor_nuevo', models.JSONField(blank=True, default=dict)),
                ('creado_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.ticket')),
            ],
            options={
                'ordering': ['creado_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_excel', models.PositiveIntegerField()),
                ('ticket_bradescard', models.CharField(blank=True, max_length=120)),
                ('accion', models.CharField(choices=[('NUEVO', 'Nuevo'), ('ACTUALIZADO', 'Actualizado'), ('SIN_CAMBIOS', 'Sin cambios'), ('ERROR', 'Error')], max_length=20)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tickets.importaciontickets')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_importacion', to='tickets.ticket')),
            ],
            options={
                'ordering': ['fila_excel'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('tipo', models.CharField(choices=[('COMENTARIO', 'Comentario'), ('INTERNO', 'Nota interna'), ('SISTEMA', 'Sistema'), ('CIERRE', 'Cierre'), ('REAPERTURA', 'Reapertura')], default='COMENTARIO', max_length=20)),
                ('creado_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('editado_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.ticket')),
            ],
            options={
                'ordering': ['creado_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tickets/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=160)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('APERTURA', 'Apertura'), ('COMENTARIO', 'Comentario'), ('CIERRE', 'Cierre'), ('EVIDENCIA', 'Evidencia')], default='EVIDENCIA', max_length=20)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_tickets', to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='tickets.comentarioticket')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='tickets.ticket')),
            ],
            options={
                'ordering': ['creado_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subgruposoporte',
            constraint=models.UniqueConstraint(fields=('grupo', 'nombre'), name='uq_subgrupo_grupo_nombre'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado_interno', 'prioridad'], name='idx_ticket_estado_pri'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tienda', 'estado_interno'], name='idx_ticket_tienda_est'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['categoria', 'incidencia_general'], name='idx_ticket_cat_inc'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['responsable', 'estado_interno'], name='idx_ticket_resp_est'),
        ),
    ]
