# Generated by Django 5.2.5 on 2026-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialticket',
            name='evento',
            field=models.CharField(choices=[('CREADO', 'Ticket creado'), ('IMPORTADO', 'Ticket importado'), ('ACTUALIZADO_IMPORTACION', 'Actualizado por importación'), ('ASIGNADO', 'Asignado'), ('PRIMER_COMENTARIO', 'Primer comentario'), ('COMENTARIO', 'Comentario'), ('ARCHIVO', 'Archivo agregado'), ('ESTADO', 'Cambio de estado'), ('PRIORIDAD', 'Cambio de prioridad'), ('GRUPO', 'Cambio de grupo'), ('SUBGRUPO', 'Cambio de subgrupo'), ('DEPENDENCIA', 'Cambio de dependencia'), ('ESTATUS_OPERATIVO', 'Cambio de estatus operativo'), ('PAUSA_SLA', 'Pausa SLA'), ('REANUDACION_SLA', 'Reanudación SLA'), ('SLA_EXCEDIDO', 'SLA excedido'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('REABIERTO', 'Reabierto')], db_index=True, max_length=40),
        ),
    ]
