# Generated by Django 5.2.5 on 2026-09-05 18:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_historialticket_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.empresa'),
        ),
        migrations.CreateModel(
            name='GrupoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_trabajo', to='tickets.empresa')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_liderados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['empresa__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personal', models.CharField(db_index=True, max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('puesto', models.CharField(blank=True, max_length=140)),
                ('horario', models.CharField(blank=True, max_length=140)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('correo', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('activa', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_operativa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('modalidad', models.CharField(choices=[('OFICINA', 'Oficina'), ('HOME_OFFICE', 'Home office'), ('HIBRIDO', 'Híbrido'), ('AUSENTE', 'Ausente')], default='OFICINA', max_length=20)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones', to='tickets.grupotrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_trabajo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('numero', models.CharField(blank=True, db_index=True, max_length=60)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(db_index=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiendas', to='tickets.empresa')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas_lideradas', to='tickets.persona')),
            ],
            options={
                'ordering': ['empresa__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='tienda_registrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.tienda'),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=180)),
                ('estado', models.CharField(db_index=True, max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='tickets.empresa')),
                ('encargado_zonal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas_encargadas', to='tickets.persona')),
            ],
            options={
                'ordering': ['empresa__nombre', 'estado', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='tienda',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiendas', to='tickets.zona'),
        ),
        migrations.AddField(
            model_name='grupotrabajo',
            name='zonas',
            field=models.ManyToManyField(blank=True, related_name='grupos_trabajo', to='tickets.zona'),
        ),
        migrations.CreateModel(
            name='AsignacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(choices=[('ESTADO', 'Estado'), ('ZONA', 'Zona'), ('TIENDA', 'Tienda')], max_length=20)),
                ('funcion', models.CharField(choices=[('COORDINADOR_ESTATAL', 'Coordinador estatal'), ('ENCARGADO_ZONAL', 'Encargado zonal'), ('LIDER_TIENDA', 'Líder de tienda'), ('PERSONAL', 'Personal')], max_length=30)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('horario', models.CharField(blank=True, max_length=140)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_personal', to='tickets.empresa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='tickets.persona')),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_personal', to='tickets.tienda')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_personal', to='tickets.zona')),
            ],
            options={
                'ordering': ['empresa__nombre', 'alcance', 'persona__nombre'],
            },
        ),
        migrations.CreateModel(
            name='MembresiaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('N1', 'Nivel 1'), ('N2', 'Nivel 2'), ('N3', 'Nivel 3')], default='N1', max_length=2)),
                ('principal', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='tickets.grupotrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_grupo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('grupo', 'usuario'), name='uq_grupo_usuario')],
            },
        ),
        migrations.AddConstraint(
            model_name='zona',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_zona_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='tienda',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_tienda_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='grupotrabajo',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='uq_grupo_empresa_nombre'),
        ),
    ]
