# Generated by Django 5.2.5 on 2026-09-05 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_empresa_ticket_empresa_grupotrabajo_persona_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importaciontickets',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importaciones_tickets', to='tickets.empresa'),
        ),
        migrations.AlterField(
            model_name='importaciontickets',
            name='hash_archivo',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_bradescard',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddConstraint(
            model_name='importaciontickets',
            constraint=models.UniqueConstraint(fields=('empresa', 'hash_archivo'), name='uq_importacion_empresa_hash'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('empresa', 'ticket_bradescard'), name='uq_ticket_empresa_externo'),
        ),
    ]
