# Generated by Django 5.2.5 on 2026-09-09 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_importaciontickets_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='agencia',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='tienda',
            name='clave',
            field=models.CharField(blank=True, db_index=True, max_length=140, verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='coordinador',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='tienda',
            name='detalle_geocodificacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tienda',
            name='encargado_soporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas_soporte_principal', to='tickets.persona'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='encargado_soporte_nombre',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='tienda',
            name='estado_geocodificacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LOCALIZADA', 'Localizada'), ('ERROR', 'No localizada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tienda',
            name='geocodificada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='gerente_distrital',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='tienda',
            name='id_externo',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID de tienda'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='lider_actual_nombre',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='tienda',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas_soporte_secundario', to='tickets.persona'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='partner_nombre',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='tienda',
            name='piloto',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='prioridad_operativa',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='tienda',
            name='retiro',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='socio',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tipo_coordinador',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=60),
        ),
        migrations.AddConstraint(
            model_name='tienda',
            constraint=models.UniqueConstraint(condition=models.Q(('id_externo', ''), _negated=True), fields=('empresa', 'id_externo'), name='uq_tienda_empresa_id_externo'),
        ),
    ]
