# Generated by Django 5.2.5 on 2026-09-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_origen_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionpersonal',
            name='incidencias',
            field=models.ManyToManyField(blank=True, help_text='Si no se selecciona ninguna, la cobertura aplica a todas las incidencias.', related_name='coberturas_operativas', to='tickets.configuracionsla'),
        ),
    ]
