# Generated by Django 5.2.5 on 2026-09-12 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_asignacionpersonal_incidencias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(model_name='ticket', name='clasificacion_manual', field=models.BooleanField(default=False)),
        migrations.AddField(
            model_name='empresa',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='grupotrabajo',
            name='actividades',
            field=models.CharField(blank=True, help_text='Ej. inventario, reparación, atención de tickets', max_length=255),
        ),
        migrations.AddField(
            model_name='grupotrabajo',
            name='atiende_tickets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grupotrabajo',
            name='incidencias',
            field=models.ManyToManyField(blank=True, related_name='equipos_actividad', to='tickets.configuracionsla'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='esperando_a',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='motivo_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='motivo_espera',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='siguiente_accion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solicitud_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='suplente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_suplencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='suplente_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='cadena',
            field=models.CharField(choices=[('BODEGA', 'Bodega'), ('PROMODA', 'Promoda'), ('GCC', 'GCC'), ('OTRA', 'Otra')], default='OTRA', max_length=12),
        ),
        migrations.AddField(
            model_name='zona',
            name='distrital_nombre',
            field=models.CharField(blank=True, max_length=180, verbose_name='Distrital de Activos'),
        ),
        migrations.AddField(
            model_name='zona',
            name='distrital_telefono',
            field=models.CharField(blank=True, max_length=40, verbose_name='Teléfono del distrital'),
        ),
        migrations.AddField(
            model_name='zona',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distritos_partner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zona',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distritos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programaciontrabajo',
            name='modalidad',
            field=models.CharField(choices=[('OFICINA', 'Oficina'), ('HOME_OFFICE', 'Home office'), ('HIBRIDO', 'Híbrido'), ('AUSENTE', 'Ausente'), ('DESCANSO', 'Descanso'), ('GUARDIA', 'Guardia')], default='OFICINA', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='segmentosla',
            constraint=models.UniqueConstraint(condition=models.Q(('fin__isnull', True)), fields=('ticket',), name='uq_sla_segmento_abierto'),
        ),
    ]
