# Generated by Django 5.2.5 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0013_evidenciaoperativa"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="descanso",
            field=models.CharField(
                blank=True,
                max_length=140,
                verbose_name="día de descanso",
            ),
        ),
    ]
