# Generated by Django 5.2.5 on 2026-09-24 17:16

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_persona_descanso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='legacy_estado',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='legacy_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='legacy_source',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_legacy_segundos',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_source__isnull', False), models.Q(('legacy_source', ''), _negated=True), ('legacy_id__isnull', False), models.Q(('legacy_id', ''), _negated=True)), fields=('legacy_source', 'legacy_id'), name='uq_ticket_legacy_source_id'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('sla_legacy_segundos__gte', 0)), name='ck_ticket_sla_legacy_no_negativo'),
        ),
    ]
