# Generated by Django 5.2.5 on 2026-09-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_legacy_ticket_sla'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='legacy_cutover_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
